config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView


urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    # accounts/signup/ must be first in order, as we want to forcefully show
    # a 404 message if the user browses to it. This is because we have our
    # own signup URLs, for medical professionals and customers.
    path("accounts/signup/", default_views.page_not_found,
        {'exception': Exception('Not Found')}, name="default-signup"),
    path("accounts/", include("allauth.urls")),
    path("users/", include("medico.users.urls", namespace="users")),
    path("consult/", include("medico.payments.urls", namespace="payments")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

medico/payments/urls.py
from django.urls import path

from medico.payments.views import checkout, consultation, modify_payment_method

app_name = "payments"
urlpatterns = [
    path("checkout/", view=checkout, name="checkout"),
    path("consultation/", view=consultation, name="consultation"),
    path("modify-payment-method/", view=modify_payment_method,
        name="modify-payment-method"),
]

medico/users/urls.py
from django.urls import path

from medico.users.views import (
    customer_signup_view,
    medical_signup_view,
    user_detail_view,
    user_redirect_view,
    user_update_view,
    cancel_subscription,
    manage_subscription
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("subscription/", view=manage_subscription, name="subscription"),
    path("cancel-subscription/", view=cancel_subscription,
        name="cancel-subscription"),
    path("customer-signup/", view=customer_signup_view, name="customer-signup"),
    path("medical-signup/", view=medical_signup_view, name="medical-signup"),
    # Note: The user detail view should be at the last, otherwise any
    # URL with "/users/something" will trigger the detail view with "something"
    # as the username, instead of the intended view.
    path("<str:username>/", view=user_detail_view, name="detail"),
]

medico/payments/models.py
from django.db import models

import medico.payments.validators as validators
import common.constants


class CheckoutInformation(models.Model):
    """
    Stores extra information not related to Stripe's models on the checkout
    page.
    """
    reason_for_visit = models.TextField(blank=True,
        max_length=common.constants.TEXTFIELD_MAX_LENGTH,
        validators=[validators.validate_max_length])
    stripe_payment_intent = models.OneToOneField("djstripe.PaymentIntent",
        on_delete=models.SET_NULL, null=True, blank=True)
    stripe_customer = models.ForeignKey("djstripe.Customer", null=True,
        on_delete=models.CASCADE, blank=True)

    class Meta:
        verbose_name_plural = "checkout information objects"

    def __str__(self):
        return "Checkout information for customer {0}"\
            .format(self.stripe_customer.name)

medico/payments/views.py
import json
import stripe
import djstripe
from djstripe.models import Product, Price

from .models import CheckoutInformation

from django.core.exceptions import ValidationError
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.urls import reverse

import common.constants
import common.decorators

common_error = 'Something went wrong. Please refresh the page or try again'\
    ' later.'


@login_required
@common.decorators.customer_only
def consultation(request):
    if "checkout_success" in request.session and \
            request.session["checkout_success"]:
        del request.session["checkout_success"]
        messages.success(request, "Your card payment was successful.")
    return render(request, "payments/consultation.html")


@login_required
@common.decorators.customer_only
def checkout(request):
    if request.method not in ['GET', 'POST']:
        return HttpResponse('Method not allowed')

    products = Product.objects.all()
    # XXX: Fix this ID in a constants file, or maybe even make it a setting
    # populated via environment.
    one_time_price = Price.objects\
        .filter(product_id=common.constants.ONE_TIME_PRODUCT_ID)\
        .last()

    if request.method == 'GET':

        return render(request, "payments/checkout.html", {
            "products": products,
            "price": one_time_price,
            # XXX: Change if production
            "STRIPE_PUBLISHABLE_KEY": settings.STRIPE_TEST_PUBLIC_KEY
        })

    elif request.method == 'POST':
        try:
            # XXX: Some sort of validation here? Add form validation maybe.
            data = json.loads(request.body)
            payment_method = data['payment_method']
            reason_for_visit = data['reason_for_visit']
            plan_id = data['plan_id']
            stripe.api_key = djstripe.settings.STRIPE_SECRET_KEY

            # Before making any Stripe calls, make sure that our checkout
            # information "checks out" (heh).
            cf_info = CheckoutInformation(reason_for_visit=reason_for_visit)
            cf_info.clean_fields()

            payment_method_obj = stripe.PaymentMethod.retrieve(payment_method)
            djstripe.models.PaymentMethod\
                .sync_from_stripe_data(payment_method_obj)
            djstripe_customer = request.user.customer\
                .get_or_create_stripe_customer(payment_method)

            if plan_id:
                # If there's a plan ID, we want to subscribe our customer to
                # that particular plan.
                djstripe_sub = request.user.customer\
                    .subscribe_stripe_customer(plan_id, djstripe_customer)
            else:
                # Otherwise we're doing a one-time checkout.
                djstripe_intent = request.user.customer\
                    .charge_stripe_customer(payment_method, djstripe_customer)
                cf_info.stripe_payment_intent = djstripe_intent

            cf_info.stripe_customer = djstripe_customer
            cf_info.save()

            request.session["checkout_success"] = True
            return JsonResponse({
                "next_url": reverse('payments:consultation'),
                "customer_id": djstripe_customer.id,
                "intent_status": "succeeded"
            })

        except ValidationError as e:
            return JsonResponse({
                "error": {
                    'message': "Please fill in all the fields in the checkout"
                               " form properly.",
                    'messages': e.messages,
                    'type': 'FormError'
                }
            }, status=400)

        except (KeyError, ValueError):
            return JsonResponse({
                "error": {
                    'message': common_error,
                    'type': 'RequestError'
                }
            }, status=400)
        except stripe.error.StripeError as e:
            # XXX: When logging is added, log `e` instances.
            return JsonResponse({
                "error":{
                    'message': e.error.message,
                    'type': 'StripeError'
                }
            }, status=500)
        except Exception as e:
            print(e)
            return JsonResponse({
                "error":{
                    'message': common_error,
                    'type': 'ServerError'
                }
            }, status=500)


@login_required
@common.decorators.customer_only
def modify_payment_method(request):
    if request.method != 'POST':
        return HttpResponse('Method not allowed')

    djstripe_customer = request.user.djstripe_customers.first()

    if not (djstripe_customer and djstripe_customer.subscription):
        return JsonResponse({
            "error": {
                'message': 'No subscription was found on this user.',
                'type': 'NotFoundError'
            }
        }, status=404)

    try:
        data = json.loads(request.body)
        payment_method = data['payment_method']
        stripe.api_key = djstripe.settings.STRIPE_SECRET_KEY

        # The payment method must be attached to both the subscription and
        # the customer.
        payment_method_obj = stripe.PaymentMethod.retrieve(payment_method)
        stripe.PaymentMethod.attach(payment_method,
            customer=djstripe_customer.id)
        djstripe.models.PaymentMethod.sync_from_stripe_data(payment_method_obj)

        stripe.PaymentMethod.attach(payment_method,
            customer=djstripe_customer.id)
        subscription = stripe.Subscription.modify(
            djstripe_customer.subscription.id,
            default_payment_method=payment_method
        )
        djstripe.models.Subscription.sync_from_stripe_data(subscription)

        return JsonResponse({
            "payment_method_id": payment_method
        })

    except (KeyError, ValueError):
        return JsonResponse({
            "error": {
                'message': common_error,
                'type': 'RequestError'
            }
        }, status=400)
    except stripe.error.StripeError as e:
        # XXX: When logging is added, log `e` instances.
        return JsonResponse({
            "error":{
                'message': e.error.message,
                'type': 'StripeError'
            }
        }, status=500)
    except Exception as e:
        print(e)
        return JsonResponse({
            "error":{
                'message': common_error,
                'type': 'ServerError'
            }
        }, status=500)


# XXX: Add a webhook to handle subscription invoicing failure (recurring
# payment failure) and fire an email off to the user offering them to
# change their payment method.

medico/users/views.py
import stripe
from allauth.account.views import SignupView

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

import common.decorators
import common.helpers
from .forms import CustomerSignupForm, MedicalProSignupForm

User = get_user_model()


class CustomerSignupView(SignupView):
    template_name = 'account/customer_signup.html'
    form_class = CustomerSignupForm
    view_name = 'customer-signup'


customer_signup_view = CustomerSignupView.as_view()


class MedicalProSignupView(SignupView):
    template_name = 'account/medical_signup.html'
    form_class = MedicalProSignupForm
    view_name = 'medical-signup'


medical_signup_view = MedicalProSignupView.as_view()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    # XXX: Add more fields in here when making a profile page where users can
    # update their details.
    fields = ["first_name", "last_name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        return reverse("users:detail",
            kwargs={"username": self.request.user.username})

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail",
            kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()


@login_required
@common.decorators.customer_only
def cancel_subscription(request):
    if request.method != 'POST':
        return HttpResponse('Method not allowed')

    djstripe_customer = request.user.djstripe_customers.first()

    if not (djstripe_customer and djstripe_customer.subscription):
        return JsonResponse({
            "error": {
                'message': 'No subscription was found on this user.',
                'type': 'NotFoundError'
            }
        }, status=404)

    sub_id = djstripe_customer.subscription.id
    try:
        # Terminate immediately by setting at_period_end False
        djstripe_customer.subscription.cancel(at_period_end=False)
    except stripe.error.StripeError as e:
        return JsonResponse({
            "error": {
                'message': e.error.message,
                'type': 'StripeError'
            }
        })

    return JsonResponse({
        "next_url": reverse('home'),
        "deleted_sub_id": sub_id
    })


@login_required
@common.decorators.customer_only
def manage_subscription(request):
    if request.method != 'GET':
        return HttpResponse('Method not allowed')

    djstripe_customer = request.user.djstripe_customers.first()
    subscription = djstripe_customer and djstripe_customer.subscription

    return render(request, "users/subscription.html", {
        "subscription": subscription and \
            common.helpers.subscription_serialize(subscription) or None,
        "card_data": subscription and \
            common.helpers.payment_method_serialize(subscription) or None,
        "STRIPE_PUBLISHABLE_KEY": settings.STRIPE_TEST_PUBLIC_KEY
    })

medico/templates/payments/checkout.html
{% extends "base.html" %}

{% block javascript %}
    {{ block.super }}
    <script src="https://js.stripe.com/v3/"></script>

{% endblock javascript %}

{% block content %}
{% comment %} Adapted from https://www.ordinarycoders.com/blog/article/django-stripe-monthly-subscription {% endcomment %}
<div class="container ">

  {% comment %} Don't show the checkout form etc. if the user is already subscribed - do this when working on doctor selection logic {% endcomment %}
  <div class="row ">
    {% for p in products %}
    <div class="col-6">
      <div class="card mx-5 shadow product-card" style="border-radius: 10px; border:none; ">
        <div class="card-body">
          <h5 class="card-title font-weight-bold">{{p.name}}</h5>
          <p class="card-text text-muted"><svg class="bi bi-check" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M10.97 4.97a.75.75 0 0 1 1.071 1.05l-3.992 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.236.236 0 0 1 .02-.022z"/>
          </svg>{{p.description}}</p>

          <fieldset>
              <div class="radio-options">
                  {% if p.plan_set.exists %}
                      {% for plan in p.plan_set.all %}
                      <input type="radio" name="{{p.name}}" value="{{plan.id}}"
                        onclick="planSelect('{{p.name}}' ,'{{plan.human_readable_price}}', '{{plan.id}}')">
                      <label for="{{ plan.id }}"><h5 >{{ plan.human_readable_price }}</h5></label>
                      {% endfor %}
                  {% else %}
                      <input type="radio" name="{{p.name}}" value="{{p.id}}"
                        onclick="planSelect('{{p.name}}' ,'{{price.human_readable_price}}', '')">
                      <label for="{{ p.id }}"><h5>{{ price.human_readable_price }}</h5></label>
                  {% endif %}
              </div>
          </fieldset>
        </div>
      </div>

    </div>

    {% endfor %}
    </div>
  </div>
  <br><br><hr><br><br>
  <div>
    <div class="row">
      <div class="col-12">
        <div class="card mx-5 shadow rounded" style="border-radius:50px;border:none">
          <div class="card-body">
            <h5 class="card-title font-weight-bold">Checkout</h5>
            <p class="text-muted ">Enter card details to book a consultation/to be subscribed immediately.</p>
            <div class="row">
              <div class="col-6 text-muted">
                <p>Plan:</p>
                <p>Total:</p>
              </div>
              <div class="col-6 text-right">
                <p id="plan"></p>
                <p id="price"></p>
                <p hidden id="priceId"></p>
              </div>

            </div>
            <br>
            <form id="checkout-form" >
              <div id="card-element" class="MyCardElement">
                <!-- Elements will create input elements here -->
              </div>

              <div class="reason-for-visit">
                <p class="text-muted">Reason for visit *</p>
                <h6 class="text-muted">If there is a cause for emergency, please go to the nearest ER or call 911</h6>
                <textarea id="reason-for-visit" required name="reason-for-visit" rows="5" cols="100"></textarea>
              </div>
              
              <!-- We'll put the error messages in this element -->
              <div id="card-errors" class="card-errors" role="alert"></div>
              <button id="submit" type="submit">
                <div class="spinner-border  spinner-border-sm text-light hidden" id="spinner" role="status">
                  <span class="sr-only">Loading...</span>
                </div>
                <span id="button-text">Pay!</span>
              </button>
            </form>
          </div>
        </div>

      </div>
    </div>
  </div>

</div>

{% endblock %}

{% block inline_javascript %}
<script type="text/javascript">
    let changeLoadingState = function(isLoading) {
      if (isLoading) {
          document.getElementById("submit").disabled = true;
          document.querySelector("#spinner").classList.remove("hidden");
          document.querySelector("#button-text").classList.add("hidden");
      } else {
          document.getElementById("submit").disabled = false;
          document.querySelector("#spinner").classList.add("hidden");
          document.querySelector("#button-text").classList.remove("hidden");
      }
    };

    let stripeElements = function() {
        stripe = Stripe("{{ STRIPE_PUBLISHABLE_KEY }}");
        let elements = stripe.elements();

        if (!document.getElementById('card-element'))
            return;

        let style = {
            base: {
                color: "#32325d",
                fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
                fontSmoothing: "antialiased",
                fontSize: "16px",
                "::placeholder": {
                    color: "#aab7c4"
                }
            },
            invalid: {
                color: "#fa755a",
                iconColor: "#fa755a"
            }
        };

        card = elements.create('card', {style: style});
        card.mount('#card-element');

        card.on('focus', function () {
            let el = document.getElementById('card-errors');
            el.classList.add('focused');
        });

        card.on('blur', function () {
            let el = document.getElementById('card-errors');
            el.classList.remove('focused');
        });

        card.on('change', function (event) {
            displayError(event);
        });

        // Add payment form handling here
        let paymentForm = document.getElementById('checkout-form');
        if (paymentForm) {
            paymentForm.addEventListener('submit', function(evt) {
                evt.preventDefault();
                // clear errors
                changeLoadingState(false);
                // Turn on the spinner
                changeLoadingState(true);

                // create new payment method and charge the user
                checkout({ card });

            });
        }
    };
    let checkout = function({ card }) {
        let billingName = "{{ user.get_full_name }}";

        // Creation of a payment method from here is unavoidable.
        // StripeJS processes its card Stripe element data in a way that
        // its python counterpart does not, which leads to the python
        // counterpart erroring if it tries to create the payment method
        // using the card element data given here.
        stripe.createPaymentMethod({
            type: 'card',
            card: card,
            billing_details: {
                name: billingName
            }
        }).then((result) => {
            if (result.error) {
                displayError(result);
                changeLoadingState(false);
            } else {
                const paymentParams = {
                    payment_method: result.paymentMethod.id,
                    reason_for_visit: document.getElementById("reason-for-visit").value,
                    plan_id: document.getElementById("priceId").innerHTML
                };

                fetch("{% url 'payments:checkout' %}", {
                    method: "POST",
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFTOKEN': '{{ csrf_token }}'
                    },
                    credentials: 'same-origin',
                    body: JSON.stringify(paymentParams)
                }).then((response) => {
                    return response.json();
                }).then((result) => {
                    if (result.error) {
                        // There was an error due to the card.
                        throw result;
                    }
                    return result;
                }).then((result) => {
                    if (result && result.intent_status === 'succeeded') {
                        window.location = result.next_url;
                    }
                    changeLoadingState(false);
                }).catch((error) => {
                    displayError(error);
                    changeLoadingState(false);
                });
            }
        });
    };

    let displayError = function(event) {
        let displayError = document.getElementById('card-errors');
        if (event.error) {
            if (event.error.type === 'FormError') {
                displayError.textContent = event.error.messages.join("\n");
            } else {
                displayError.textContent = event.error.message;
            }
        } else {
            displayError.textContent = '';
        }
    };

    let planSelect = function(name, price, planId) {
        var inputs = document.getElementsByTagName('input');

        // Deselect one time payment if a subscription plan is
        // selected and vice versa.
        for (var i = 0; i < inputs.length; i++) {
            if (inputs[i].name !== name) {
                inputs[i].checked = false;
            }
        }

        // Set up plan display inside card form.
        var n = document.getElementById('plan'),
            p = document.getElementById('price'),
            pid = document.getElementById('priceId'),
            buttonText = document.getElementById('button-text');

        n.innerHTML = name;
        p.innerHTML = price;

        if (planId) {
            pid.innerHTML = planId;
            buttonText.innerHTML = "Subscribe!"
        } else {
            pid.innerHTML = "";
            buttonText.innerHTML = "Pay!"
        }
        document.getElementById("submit").disabled = false;
    };

    stripeElements();
    // Keep the button disabled until a plan is selected
    document.getElementById("submit").disabled = true;

</script>
{% endblock inline_javascript %}

medico/templates/payments/consultation.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<p>Congratulations, you are now on the chat page.</p>
<p>We don't have the chat system up yet however.</p>
<img src="{% static 'images/please_stand_by.jpeg' %}" />
{% endblock content %}